# 2018-10-13 (cc) <paul4hough@gmail.com>
#
---
pkgs:
  python_dev:
    Ubuntu:
      - python3
      - python3-dev
      - python3-pip
  ansible_dev:
    Ubuntu:
      - build-essential
      - libffi-dev
      - libre2-dev
      - libssl-dev

pips:
  python_dev:
    - pytest
    - tox
  ansible_dev:
    - ansible
    - molecule
    - testinfra
