# 2018-10-24 (cc) <paul4hough@gmail.com>
#
---
pkgs:
  Common:
    - xterm
    - emacs
    - xpdf
    - fbreader # epub
    - feh
    - xload
    - uni2ascii
  Debian:
    - x11-apps
    - x11-utils
  Dist:
    - Ubuntu:
      - ubuntu-restricted-extras
