# 2018-10-24 (cc) <paul4hough@gmail.com>
#
---
pkgs:
  Common:
    - automake
    - gcc
    - emacs-x11
    - git
    - iftop
    - lsof
    - lynx
    - make
    - nmap
    - sysstat
    - unar
    - xterm
  Debian:
    - g++
  Suse:
    - gcc-c++
