# 2018-11-21 (cc) <paul4hough@gmail.com>
#
---
# postfix
# sudo apt-get install libsasl2-modules postfix
paul4local@gmail.com
pah4Local!

lkzo vgtf sdfr lnbh
lkzovgtfsdfrlnbh


/etc/postfix/sasl/sasl\\_passwd
1
[smtp.gmail.com]:587 username@gmail.com:password

relayhost = [smtp.gmail.com]:587
sudo postmap /etc/postfix/sasl/sasl_passwd


/etc/postfix/main.cf

 1
 2
 3
 4
 5
 6
 7
 8
 9
10
# Enable SASL authentication
smtp_sasl_auth_enable = yes
# Disallow methods that allow anonymous authentication
smtp_sasl_security_options = noanonymous
# Location of sasl_passwd
smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd
# Enable STARTTLS encryption
smtp_tls_security_level = encrypt
# Location of CA certificates
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt